### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by osmium-dev** [thien-do/samuwrite.com#143]
# Overview
I tried saving, but I got this error:
![image](https://user-images.githubusercontent.com/99157490/186693228-2ebe12d2-ce82-497a-932e-2dfff88dca69.png)

# Device
* Web version
* Windows 11

**Comment by osmium-dev** [comment]
I would very much like to fix this error, I'm just not sure if you accept contributions as there's no `CONTRIBUTION.md` file and this all seems like a between friend project.

**Comment by thien-do** [comment]
Hello @osmium-dev sorry I'm gladly surprised you found the project 😅 I'm just building it now and everything indeed is not working completely

> I would very much like to fix this error, I'm just not sure if you accept contributions as there's no CONTRIBUTION.md file and this all seems like a between friend project.

It's more than welcome haha, and sorry for not having prepared the proper docs. A quick start would be to clone this project locally, and `npm install` then `npm run dev`. If you see it, you can hack it!

> I tried saving, but I got this error:

This is actually because samuwrite is built for 2 platform: web and mac. They actually share the same source with just some small differences. One of the differences is that the Mac version should save natively (which we do support) but the Web version should save using the new File API (https://web.dev/file-system-access/) which we did not support yet, thus the error

**Comment by osmium-dev** [comment]
Oh ok, I see. Well I'll try to fix this if it hasn't been already whenever I'll be free. 👌

**Comment by osmium-dev** [comment]
I'm currently working on it.

**Comment by thien-do** [comment]
Thanks @osmium-dev
